### ISSUE TITLE
position

### ISSUE THREAD

**Issue by wymxz** [ofirpress/sandwich_transformer#1]
原先的position只是在input中相加，key_pe 每个transform_lay都加了，这样做有什么好处？
下面这部分的代码什么功能，我看不懂，可以介绍一下吗
def _skew(X, pad_value):
    """shift every row 1 step to right"""
    # X = B x M x L
    B, M, L = X.size()
    X = F.pad(X, (0, M + 1), value=pad_value)  # B x M x (L+M+1)
    X = X.view(B, -1)  # B x ML+MM+M
    X = X[:, :-M]  # B x ML+MM
    X = X.view(B, M, M + L)  # B x M x L+M
    return X

def _unskew(X):
    """reverse _skew operation"""
    # X = B x M x L+M
    B, M, L = X.size()
    L -= M
    X = X.view(B, -1)  # B x ML+MM
    X = F.pad(X, (0, M))  # B x ML+MM+M
    X = X.view(B, M, M + L + 1)  # B x M x L+M+1
    X = X[:, :, :L]  # B x M x L
    return X

**Comment by ofirpress** [comment]
This code is based on the adaptive attention span model that can be found here https://github.com/facebookresearch/adaptive-span
